[tool.poetry]
name = "tensorlake"
version = "0.1.0"
description = "Petabyte scale data framework for unstructured data of any modality"
authors = ["Tensorlake Devs <info@tensorlake.ai>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
tensorlake = "tensorlake.cli:tensorlake"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
