name: Build and Publish to PyPI

on:
  workflow_dispatch:


permissions:
  contents: write
  actions: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tensorlake
    permissions:
      id-token: write  # Required for OIDC authentication to PyPI

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # Try workaround private repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.0
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run tests
        run: |
          make test
        
      # TODO: Re-enable once executor has been migrated
      # - name: Build package
      #   run: |
      #     poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
