name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - 'main'
    paths:
      - 'tensorlake/**'
      - 'tests/**'
      - '.github/workflows/tests.yaml'

jobs:
  lint_python_packages:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Build and lint tensorlake
        run: make build && make check

        # TODO: Needed for compose, remove when compose is migrated to use public images
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-platform-api
          aws-region: ${{ vars.AWS_REGION }}

        # TODO: Needed for compose, remove when compose is migrated to use public images          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./tests/compose.yaml"

      - name: Run tests
        env:
          INDEXIFY_URL: http://127.0.0.1:8900
        run: make test
