name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - 'main'
    paths:
      - 'tensorlake/**'
      - '.github/workflows/tests.yaml'

jobs:
  lint_python_packages:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Build and lint tensorlake
        run: make build && make check

      - name: Run tests
        run: make tests